=== Artheau/SpriteSomething/resources/app/meta/manifests/meta-language.schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "$id": "https://raw.githubusercontent.com/Artheau/SpriteSomething/master/resources/app/meta/manifests/meta-language.schema.json",
  "type": "object",
  "title": "SpriteSomething Meta Translation File Schema",
  "description": "Required strings for translation",
  "required": [
    "menu",
    "dialogue",
    "meta",
    "tab",
    "vcr-controls"
  ],
  "properties": {
    "menu": {
      "$id": "#/properties/menu",
      "type": "object",
      "title": "The Menu Schema",
      "required": [
        "file",
        "file.open",
        "file.save",
        "file.exit",
        "export",
        "export.inject",
        "export.inject-new",
        "export.inject-bulk",
        "export.frame-as-png",
        "export.animation-as-gif",
        "export.animation-as-hcollage",
        "export.animation-as-vcollage",
        "tools",
        "tools.palette-editor",
        "plugins",
        "plugins.game",
        "plugins.sprite",
        "help",
        "help.diagnostics",
        "help.about"
      ],
      "items": {
        "$id": "#/properties/menu/items",
        "type": "string",
        "title": "The Menu Items Schema",
        "pattern": "^(.*)$"
      }
    },
    "dialogue": {
      "$id": "#/properties/dialogue",
      "type": "object",
      "title": "The Dialogue Schema",
      "required": [
        "file.open.title",
        "file.open.types.label",
        "file.save.title",
        "file.save.png",
        "file.save.zspr",
        "file.save.rdc",
        "export.inject.title",
        "export.inject.types",
        "export.source.title",
        "export.source.types",
        "export.inject-new.title",
        "export.inject-new.types",
        "export.frame-as-png",
        "export.animation-as-hcollage",
        "export.animation-as-vcollage",
        "open.save-before-open",
        "open.save-failed-during-open-attempt",
        "exit.save-before-exit",
        "exit.nosave-before-exit",
        "exit.save-failed-during-exit-attempt"
      ],
      "items": {
        "$id": "#/properties/dialogue/items",
        "type": "string",
        "title": "The Dialogue Items Schema",
        "pattern": "^(.*)$"
      }
    },
    "meta": {
      "$id": "#/properties/meta",
      "type": "object",
      "title": "The Meta Schema",
      "required": [
        "none",
        "reload",
        "sprite.name",
        "author.name",
        "author.name-short",
        "background",
        "animations"
      ],
      "items": {
        "$id": "#/properties/meta/items",
        "type": "string",
        "title": "The Meta Items Schema Schema",
        "pattern": "^(.*)$"
      }
    },
    "tab": {
      "$id": "#/properties/tab",
      "type": "object",
      "title": "The Tab Schema",
      "required": [
        "animations",
        "overview"
      ],
      "items": {
        "$id": "#/properties/tab/items",
        "type": "string",
        "title": "The Tab Items Schema",
        "pattern": "^(.*)$"
      }
    },
    "vcr-controls": {
      "$id": "#/properties/vcr-controls",
      "type": "object",
      "title": "The VCR Controls Schema",
      "required": [
        "zoom-minus",
        "zoom-plus",
        "speed-minus",
        "speed-plus",
        "play",
        "play-one",
        "reset",
        "frame-backward",
        "pause",
        "frame-forward",
        "pose-backward",
        "pose-forward"
      ],
      "items": {
        "$id": "#/properties/vcr-controls/items",
        "type": "string",
        "title": "The VCR Controls Items Schema",
        "pattern": "^(.*)$"
      }
    }
  }
}

=== Artheau/SpriteSomething/app_resources/meta/lang/en.json
{
  "menu": {
    "file": "File",
    "file.open": "Open",
    "file.save": "Save As...",
    "file.exit": "Exit",
    "export": "Export",
    "export.inject": "Inject into Game File",
    "export.inject-new": "Copy to new Game File",
    "export.inject-bulk": "Inject into directory of Game Files",
    "export.frame-as-png": "Frame as PNG",
    "export.animation-as-gif": "Animation as GIF",
    "export.animation-as-hcollage": "Animation as Horizontal Collage",
    "export.animation-as-vcollage": "Animation as Vertical Collage",
    "tools": "Tools",
    "tools.palette-editor": "Palette Editor",
    "plugins": "Plugins",
    "plugins.game": "Game",
    "plugins.sprite": "Sprite",
    "help": "Help",
    "help.diagnostics": "Diagnostics",
    "help.about": "About"
  },
	"dialogue": {
		"file.open.title": "Select Sprite",
		"file.open.types.label": "Supported Types",
		"file.save.title": "Save Sprite As...",
		"file.save.png": "Portable Network Graphics",
		"file.save.zspr": "ZSPR Sprite",
		"file.save.rdc": "Retro Data Container",
		"export.inject.title": "Select ROM to Modify...",
		"export.inject.types": "Game Files",
		"export.source.title": "Select Source ROM",
		"export.source.types": "Game Files",
		"export.inject-new.title": "Save Modified ROM As...",
		"export.inject-new.types": "Game Files",
		"export.frame-as-png": "Save Frame As...",
		"export.animation-as-hcollage": "Save Horizontal Collage As...",
		"export.animation-as-vcollage": "Save Vertical Collage As...",
        "open.save-before-open": "You have unsaved changes.\n\nDo you want to save before opening a new file?",
        "open.save-failed-during-open-attempt": "The file was NOT saved.",
		"exit.save-before-exit": "You have unsaved changes.\n\nDo you want to save before exiting?",
		"exit.nosave-before-exit": "Death in Super Metroid loses progress since last save.\nYou have been eaten by a grue.",
        "exit.save-failed-during-exit-attempt": "The file was NOT saved successfully.  Do you want to exit anyway?"
	},
  "meta": {
    "none": "None",
    "reload": "Reload",
    "sprite.name": "Sprite Name",
    "author.name": "Author Name",
    "author.name-short": "Author Name Short",
    "background": "Background",
    "animations": "Animations"
  },
  "tab": {
    "animations": "Animations",
    "overview": "Overview"
  },
  "vcr-controls": {
    "zoom-minus": "Zoom -",
    "zoom-plus": "Zoom +",
    "speed-minus": "Speed -",
    "speed-plus": "Speed +",
    "play": "Play",
    "play-one": "Play 1",
    "reset": "Reset",
    "frame-backward": "Frame",
    "pause": "Pause",
    "frame-forward": "Frame",
    "pose-backward": "Pose",
    "pose-forward": "Pose"
  }
}
