=== Artheau/SpriteSomething/resources/app/snes/metroid3/samus/manifests/samus-language.schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "$id": "https://raw.githubusercontent.com/Artheau/SpriteSomething/master/resources/app/metroid3/samus/manifests/samus-language.schema.json",
  "type": "object",
  "title": "SpriteSomething Metroid3 Samus Sprite Translation File Schema",
  "description": "Required strings for translation",
  "required": [
    "section",
    "Aiming",
    "Facing",
    "Suit",
    "Variant",
    "Cannon Port"
  ],
  "properties": {
    "section": {
      "$id": "#/properties/section",
      "type": "object",
      "title": "The Section Schema",
      "required": [
        "aiming",
        "facing",
        "suit",
        "variant",
        "cannon-port"
      ],
      "items": {
        "$id": "#/properties/section/items",
        "type": "string",
        "title": "The Section Items Schema",
        "pattern": "^(.*)$"
      }
    },
    "Aiming": {
      "$id": "#/properties/Aiming",
      "type": "object",
      "title": "The Aiming Schema",
      "required": [
        "up",
        "diag_up",
        "neutral",
        "shoot",
        "diag_down",
        "down"
      ],
      "items": {
        "$id": "#/properties/Aiming/items",
        "type": "string",
        "title": "The Aiming Items Schema",
        "pattern": "^(.*)$"
      }
    },
    "Facing": {
      "$id": "#/properties/Facing",
      "type": "object",
      "title": "The Facing Schema",
      "required": [
        "left",
        "right"
      ],
      "items": {
        "$id": "#/properties/Facing/items",
        "type": "string",
        "title": "The Facing Items Schema",
        "pattern": "^(.*)$"
      }
    },
    "Suit": {
      "$id": "#/properties/Suit",
      "type": "object",
      "title": "The Suit Schema",
      "required": [
        "power",
        "varia",
        "gravity"
      ],
      "items": {
        "$id": "#/properties/Suit/items",
        "type": "string",
        "title": "The Suit Items Schema",
        "pattern": "^(.*)$"
      }
    },
    "Variant": {
      "$id": "#/properties/Variant",
      "type": "object",
      "title": "The Variant Schema",
      "required": [
        "standard",
        "charge",
        "speed_boost",
        "speed_squat",
        "hyper",
        "heat",
        "xray",
        "sepia",
        "door"
      ],
      "items": {
        "$id": "#/properties/Variant/items",
        "type": "string",
        "title": "The Variant Items Schema",
        "pattern": "^(.*)$"
      }
    },
    "Cannon Port": {
      "$id": "#/properties/Cannon Port",
      "type": "object",
      "title": "The Cannon port Schema",
      "required": [
        "no",
        "yes"
      ],
      "items": {
        "$id": "#/properties/Cannon Port/items",
        "type": "string",
        "title": "The Cannon Port Items Schema",
        "pattern": "^(.*)$"
      }
    }
  }
}

=== Artheau/SpriteSomething/resources/user/snes/metroid3/samus/lang/es.json
{
	"$schema": "../../../../../../resources/app/snes/metroid3/samus/manifests/samus-language.schema.json",
	"section": {
		"aiming": "Aiming",
		"facing": "Facing",
		"suit": "Suit",
		"variant": "Variant",
		"cannon-port": "Cannon Port"
	},
	"Aiming": {
		"up": "Arriba",
		"diag_up": "Diagonal hacia Arriba",
		"neutral": "Neutral",
		"shoot": "Disparar",
		"diag_down": "Diagonal hacia Abajo",
		"down": "Abajo"
	},
	"Facing": {
		"left": "Izquierda",
		"right": "Derecha"
	},
	"Suit": {
		"power": "Traje Chozo",
		"varia": "Traje Climático",
		"gravity": "Traje Gravitatorio"
	},
	"Variant": {
		"none": "Ninguno",
		"standard": "Estándar",
		"charge": "Rayo Recargar",
		"speed_boost": "Aceleración",
		"speed_squat": "Sentadilla con Energía",
		"hyper": "Hiperrayo",
		"heat": "Calor",
		"xray": "Radiografía",
		"sepia": "Sepia",
		"door": "Puerta"
	},
	"Cannon Port": {
		"no": "Cerrado",
		"yes": "Abierto"
	}
}
